### ISSUE TITLE
Question about spawning mplayer processes

### ISSUE THREAD

**Issue by shangsunset** [mafintosh/deejay#5]
Hi mafintosh,

I'm learning node from your code and i cant understand below code. Do you mind giving me a brief explanation?
`var proc = spawn('mplayer', [].concat(argv['--'] || []).concat('-'), {stdio: [null, 'inherit', 'inherit']})`

I know this line spawns a shell command to run mplayer but why is option field `['-']` by default? i tried `const child = spawn('mplayer', [filename], { stdio: [null, 'inherit', 'inherit'] })` but got error: 

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:856:11)
    at WriteWrap.afterWrite (net.js:767:14)
```

Thanks.

**Comment by mafintosh** [comment]
the `-` argument here tells mplayer to read from stdin. that way we can pipe to `child.stdin` in node

``` js
// - means read from stdin. the "inherits" string makes spawn forward stderr, stdout to our terminal
var child = spawn('mplayer', ['-'], {stdio: [null, 'inherits', 'inherits']})

someStream.pipe(child.stdin)
```

makes sense?

**Comment by shangsunset** [comment]
I see. That helps a lot.
one more question. i ran the program, but the music doesnt play from the beginning. any reason why that happens? does it have anything to do with reading from `child.stadin`?

Thanks.
